Repository koreatrip/korip-frontend, pull requests merged in 2025-07, with the labels that each got.

#29 [Style]date tab
  src/components/MyPage/Modals/AccountDeleteModal.tsx
  src/components/common/DateRangePicker.tsx
  src/components/common/Tab.tsx
  src/components/domain/planner/DailyScheduleTabs.tsx
  src/components/domain/planner/DailyTimeline.tsx
  src/components/domain/planner/DraggablePlaceCard.tsx
  src/components/domain/planner/PlannerSidebar.tsx
  src/components/domain/planner/SchedulePlanner.tsx
  src/components/domain/planner/SelectedPlacesList.tsx
  src/components/domain/planner/TimeSlot.tsx
  src/pages/plannerPage.tsx
  src/stores/usePlannerStore.ts
  src/types/plannerType.ts
  tsconfig.app.json
Labels: 💄style, 🚚 Rename, 🔥 Remove, 우선순위: 🟡 중간, ✨Feature, 🐛Bug

#38 [feat] 기상청 api mws 작업
  .env
  package.json
  src/api/locations/locationAPI.ts
  src/api/locations/locationHooks.ts
  src/api/locations/locationQueries.ts
  src/api/locations/locationType.ts
  src/api/regions/locationHooks.ts
  src/components/common/searchBar/SearchBar.tsx
  src/components/domain/regions/DistrictCard.tsx
  src/components/domain/regions/InfoCard.tsx
  src/components/domain/weather/AirQuality.tsx
  src/components/domain/weather/HourlyForecast.tsx
  src/components/domain/weather/Weather.tsx
  src/components/domain/weather/WeatherDetail.tsx
  src/components/domain/weather/WeatherSkeleton.tsx
  src/context/ToastContextProvider.tsx
  src/data/korea-administrative-district.json
  src/hooks/useWeather.ts
  src/layouts/defaultLayout.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/mockWeatherLocationHandlers.ts
  src/pages/regionsPage.tsx
  src/stores/useLocationStore.ts
  src/utils/weatherUtils.ts
  src/utils/순수함수만
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 💄style, 우선순위: 🟡 중간, ✨Feature

#41 Feat/subcategory msw search UI
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/category/categoryAPI.ts
  src/api/category/categoryHooks.ts
  src/api/category/categoryQueries.ts
  src/api/category/categoryType.ts
  src/api/regions/locationHooks.ts
  src/components/MyPage/Modals/AccountDeleteModal.tsx
  src/components/common/Modal.tsx
  src/components/common/searchBar/SearchBar.tsx
  src/components/domain/regions/Tag.tsx
  src/components/ui/TagSkeleton.tsx
  src/context/ToastContextProvider.tsx
  src/hooks/useWeather.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/mockCategoriesHandler.ts
  src/pages/districtListPage.tsx
  src/pages/regionsPage.tsx
  src/router/index.tsx
  yarn.lock
Labels: 💄style, 우선순위: 🟡 중간, ✨Feature

#48 [Feat] 첫번째 지역 탐색 페이지
  src/components/common/Header.tsx
  src/components/domain/regions/CarouselForCard.tsx
  src/components/domain/regions/FirstInfoCard.tsx
  src/pages/firstSearchingPage.tsx
  src/router/index.tsx
Labels: 💄style
