Repository koreatrip/korip-frontend, pull requests merged in 2025-06, with the labels that each got.

#4 Style/ 공용 컴포넌트 UI
  index.html
  package.json
  src/App.css
  src/App.tsx
  src/assets/assets.ts
  src/assets/header/logo_sm.svg
  src/components/Components
  src/components/auth/AuthInput.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/ToastMessage.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/header/Header.tsx
  src/components/header/SearchHeader.tsx
  src/components/searchBar/SearchBar.tsx
  src/components/sideMenu/SideMenu.tsx
  src/context/ToastContextProvider.tsx
  src/hooks/useHooks
  src/hooks/useToast.tsx
  src/index.css
  src/layouts/defaultLayout.tsx
  src/layouts/memberLoginLayout
  src/router/index.tsx
  src/stores/useHeaderStore.ts
  src/stores/useStore
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 💄style, 우선순위: 🟢 낮음

#7 [Style] 공통 브레이크 포인트 설정 #6 (긴급)
  package-lock.json
  src/index.css
  src/pages/loginPage
  src/pages/loginPage.tsx
  src/router/index.tsx
  yarn.lock
Labels: 우선순위: 🔴 긴급

#13 [Style] 모달 ui,모든구역,일정계획 페이지 ui작업
  src/assets/assets.ts
  src/assets/star/star_full_sm.svg
  src/assets/star/star_sm.svg
  src/components/common/Accordion.tsx
  src/components/common/Container.tsx
  src/components/common/DateRangePicker.tsx
  src/components/common/Header.tsx
  src/components/common/Modal.tsx
  src/components/common/Tab.tsx
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/searchBar/SearchBar.tsx
  src/components/common/sideMenu/SideMenu.tsx
  src/components/domain/auth/AuthInput.tsx
  src/components/domain/auth/LoginPromptModal.tsx
  src/components/domain/login/LoginForm.tsx
  src/components/domain/login/SocialLoginButtons.tsx
  src/components/domain/login/WelcomeCard.tsx
  src/components/domain/planner/DailyScheduleTabs.tsx
  src/components/domain/planner/DailyTimeline.tsx
  src/components/domain/planner/DraggablePlaceCard.tsx
  src/components/domain/planner/PlannerMap.tsx
  src/components/domain/planner/PlannerSidebar.tsx
  src/components/domain/planner/SchedulePlanner.tsx
  src/components/domain/planner/SelectedPlacesList.tsx
  src/components/domain/planner/TimeSlot.tsx
  src/components/domain/planner/TripSummary.tsx
  src/components/domain/regions/Carousel.tsx
  src/components/domain/regions/DistrictCard.tsx
  src/components/domain/regions/InfoCard.tsx
  src/components/domain/regions/PlaceDetailModal.tsx
  src/components/domain/weather/AirQuality.tsx
  src/components/domain/weather/HourlyForecast.tsx
  src/components/domain/weather/TravelTips.tsx
  src/components/domain/weather/Weather.tsx
  src/components/domain/weather/WeatherDetail.tsx
  src/components/header/Header.tsx
  src/components/header/SearchHeader.tsx
  src/layouts/defaultLayout.tsx
  src/layouts/searchLayout.tsx
  src/pages/districtListPage.tsx
  src/pages/examplePage.tsx
  src/pages/loginPage.tsx
  src/pages/plannerPage.tsx
  src/pages/regionsPage.tsx
  src/pages/travelTipsPage.tsx
  src/router/index.tsx
  src/types/tabType.ts
Labels: 💄style, 🚚 Rename, 🍱 Add, 우선순위: 🟡 중간, ♻️ Refactor
